"""Embed synthetic-disclaimer PNG metadata."""

from __future__ import annotations

from pathlib import Path

from PIL import Image
from PIL.PngImagePlugin import PngInfo


def stamp_synthetic(path: Path, *, prompt: str | None = None, seed: int | None = None) -> None:
    img = Image.open(path)
    info = PngInfo()
    info.add_text("Software", "fakeperson")
    info.add_text("Disclaimer", "synthetic")
    info.add_text("Synthetic", "true")
    info.add_text("Comment", "This image depicts a fictional person generated by fakeperson.")
    if prompt:
        info.add_text("Prompt", prompt[:2000])
    if seed is not None:
        info.add_text("Seed", str(seed))
    # Preserve mode; always write PNG
    out = path if path.suffix.lower() == ".png" else path.with_suffix(".png")
    img.save(out, pnginfo=info)
    if out != path and path.exists() and path.suffix.lower() != ".png":
        path.unlink(missing_ok=True)
